// Barrel generator for per-project custom element modules.
//
// Remotion's renderer is build-time: Webpack bundles everything reachable
// from src/index.ts and serves the output as a headless-Chrome page. There
// is no filesystem at render time, so truly-dynamic imports don't work for
// `mv:render`. Instead, we generate a barrel file in the source tree just
// before bundling, pointing at the active project's custom elements, and
// reset it afterward so the source tree stays clean.
//
// The barrel's module path is consumed by
// src/compositions/elements/registry.ts which imports
// PROJECT_CUSTOM_ELEMENTS and merges them with the engine library.

import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { basename, extname, relative, resolve } from "node:path";

export const BARREL_PATH_FROM_REPO_ROOT =
  "src/compositions/elements/_generated-custom-elements.ts";

const EMPTY_BARREL = `// biome-ignore-all lint/suspicious/noExplicitAny: intentional — heterogeneous module list
//
// Auto-generated by scripts/cli/custom-elements-barrel.ts.
// Do NOT edit by hand — mv:render rewrites this before every render based
// on the active project's projects/<stem>/custom-elements/*.tsx and resets
// it to empty on exit.

import type { ElementModule } from "./types";

export const PROJECT_CUSTOM_ELEMENTS: ElementModule<any>[] = [];
`;

const writeBarrel = (repoRoot: string, body: string): void => {
  const p = resolve(repoRoot, BARREL_PATH_FROM_REPO_ROOT);
  writeFileSync(p, body);
};

export const resetCustomElementsBarrel = (repoRoot: string): void => {
  writeBarrel(repoRoot, EMPTY_BARREL);
};

// Scan <projectDir>/custom-elements/ for *.tsx files. For each file, emit
// an import that grabs the default export (or a named export matching the
// convention "<PascalName>Module"). Consumer authors export either:
//   export default MyCustomModule          → preferred
//   export const MyPascalNameModule: ...   → fallback, matched by filename
//
// We prefer the default export for simplicity and to avoid name-drift. If
// a project wants named exports for type-narrowing, they can re-export as
// default in the same file.
export const generateCustomElementsBarrel = (
  repoRoot: string,
  projectDir: string,
): { moduleCount: number; files: string[] } => {
  const customDir = resolve(projectDir, "custom-elements");
  if (!existsSync(customDir)) {
    resetCustomElementsBarrel(repoRoot);
    return { moduleCount: 0, files: [] };
  }
  const entries = readdirSync(customDir)
    .filter((f) => f.endsWith(".tsx") && !f.startsWith("."))
    .sort();
  if (entries.length === 0) {
    resetCustomElementsBarrel(repoRoot);
    return { moduleCount: 0, files: [] };
  }

  const barrelAbsPath = resolve(repoRoot, BARREL_PATH_FROM_REPO_ROOT);
  const lines: string[] = [
    "// biome-ignore-all lint/suspicious/noExplicitAny: intentional — heterogeneous module list",
    "//",
    "// Auto-generated by scripts/cli/custom-elements-barrel.ts.",
    "// Do NOT edit by hand — mv:render rewrites this before every render based",
    "// on the active project's projects/<stem>/custom-elements/*.tsx and resets",
    "// it to empty on exit.",
    "",
    'import type { ElementModule } from "./types";',
  ];

  const importNames: string[] = [];
  entries.forEach((file, i) => {
    const stem = basename(file, extname(file));
    const ident = `_proj_${i}_${stem.replace(/[^a-zA-Z0-9_]/g, "_")}`;
    importNames.push(ident);
    const importPath = relative(resolve(barrelAbsPath, ".."), resolve(customDir, file))
      .replace(/\\/g, "/")
      .replace(/\.tsx$/, "");
    lines.push(
      `import ${ident} from "${importPath.startsWith(".") ? importPath : "./" + importPath}";`,
    );
  });

  lines.push(
    "",
    "export const PROJECT_CUSTOM_ELEMENTS: ElementModule<any>[] = [",
    ...importNames.map((n) => `  ${n},`),
    "];",
    "",
  );

  writeBarrel(repoRoot, lines.join("\n"));
  return { moduleCount: entries.length, files: entries };
};
