// biome-ignore-all lint/suspicious/noExplicitAny: intentional — heterogeneous module list
//
// Auto-generated by scripts/cli/mv-render.ts before each render. Do NOT edit
// by hand — changes will be clobbered on the next `mv:render`. This file is
// gitignored so the barrel reflects the currently-rendering project only.
//
// Per-project custom elements live at `projects/<stem>/custom-elements/*.tsx`
// and are surfaced to the renderer via this barrel. See
// `projects/_plans/HOW-TO-ADD-AN-ELEMENT.md` (and per-project README in
// `custom-elements/`) for the authoring contract.

import type { ElementModule } from "./types";

export const PROJECT_CUSTOM_ELEMENTS: ElementModule<any>[] = [];
