// biome-ignore-all lint/suspicious/noExplicitAny: intentional — heterogeneous module list
//
// Auto-generated by scripts/cli/custom-elements-barrel.ts.
// Do NOT edit by hand — mv:render rewrites this before every render based
// on the active project's projects/<stem>/custom-elements/*.tsx and resets
// it to empty on exit.

import type { ElementModule } from "./types";

export const PROJECT_CUSTOM_ELEMENTS: ElementModule<any>[] = [];
